"""Small shared helpers: monotonic wall-clock in ms, id generation, hashing."""

from __future__ import annotations

import hashlib
import hmac
import secrets
import time


def now_ms() -> int:
    """Unix time in milliseconds. The one time unit the whole system speaks."""
    return int(time.time() * 1000)


def gen_cmd_id() -> str:
    """A short, unique correlation id echoed by the node in results and output."""
    return "c_" + secrets.token_hex(4)


def gen_token() -> str:
    """A fresh shared node token. Shown once, stored only as a hash."""
    return secrets.token_urlsafe(24)


def gen_nonce() -> str:
    """A ping nonce for RTT correlation."""
    return secrets.token_hex(4)


def hash_token(token: str) -> str:
    """Hash a HIGH-ENTROPY bearer token for storage. The plaintext is never
    persisted.

    This is for the node token, which is generated by gen_token()
    (secrets.token_urlsafe(24) = 192 bits of entropy) — NOT a human-chosen
    password. A plain SHA-256 is appropriate here: the slow, memory-hard KDFs
    (scrypt/bcrypt/argon2) exist to defend LOW-entropy human passwords against
    brute force, and buy nothing against a 192-bit random token, where the
    keyspace is already infeasible to search regardless of hash speed. Verifying
    a token on every node connection with a deliberately expensive KDF would only
    add latency. For human passwords use hash_password()/verify_password() below.
    """
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def token_matches(token: str, stored_hash: str) -> bool:
    """Constant-time compare of a presented token against the stored hash."""
    if not stored_hash:
        return False
    return hmac.compare_digest(hash_token(token), stored_hash)


# scrypt work factors. n=2**14 keeps a verify well under ~100ms while making a
# brute-force of a weak password memory-hard. maxmem is sized above 128*n*r*p.
_SCRYPT_N, _SCRYPT_R, _SCRYPT_P = 1 << 14, 8, 1
_SCRYPT_MAXMEM = 64 * 1024 * 1024


def hash_password(password: str, salt: bytes = None) -> str:
    """Hash a HUMAN password with a memory-hard KDF (scrypt) and a random salt.

    Returns 'scrypt$n$r$p$salt_hex$hash_hex'. Use this — never hash_token — for
    operator/login credentials, which are low-entropy and must resist offline
    brute force even if the settings store leaks."""
    if salt is None:
        salt = secrets.token_bytes(16)
    dk = hashlib.scrypt(password.encode("utf-8"), salt=salt, n=_SCRYPT_N,
                        r=_SCRYPT_R, p=_SCRYPT_P, maxmem=_SCRYPT_MAXMEM, dklen=32)
    return "scrypt$%d$%d$%d$%s$%s" % (_SCRYPT_N, _SCRYPT_R, _SCRYPT_P, salt.hex(), dk.hex())


def verify_password(password: str, stored: str) -> bool:
    """Constant-time verify of a password against a hash_password() string."""
    if not stored:
        return False
    try:
        scheme, n, r, p, salt_hex, hash_hex = stored.split("$")
        if scheme != "scrypt":
            return False
        dk = hashlib.scrypt(password.encode("utf-8"), salt=bytes.fromhex(salt_hex),
                            n=int(n), r=int(r), p=int(p), maxmem=_SCRYPT_MAXMEM,
                            dklen=len(hash_hex) // 2)
    except (ValueError, AttributeError):
        return False
    return hmac.compare_digest(dk.hex(), hash_hex)
